
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowComumReclamante(object):
    def setupUi(self, WindowComumReclamante):
        WindowComumReclamante.setObjectName("WindowComumReclamante")
        WindowComumReclamante.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(WindowComumReclamante)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textoNome_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_9.setFont(font)
        self.textoNome_9.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_9.setObjectName("textoNome_9")
        self.gridLayout_2.addWidget(self.textoNome_9, 11, 2, 1, 1)
        self.inputAdvogado = QtWidgets.QLineEdit(self.tab)
        self.inputAdvogado.setObjectName("inputAdvogado")
        self.gridLayout_2.addWidget(self.inputAdvogado, 11, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 12, 2, 1, 1)
        self.textoNome = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome.setFont(font)
        self.textoNome.setTextFormat(QtCore.Qt.RichText)
        self.textoNome.setObjectName("textoNome")
        self.gridLayout_2.addWidget(self.textoNome, 2, 2, 1, 1)
        self.textoNome_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_3.setFont(font)
        self.textoNome_3.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_3.setObjectName("textoNome_3")
        self.gridLayout_2.addWidget(self.textoNome_3, 4, 2, 1, 1)
        self.inputNome = QtWidgets.QLineEdit(self.tab)
        self.inputNome.setObjectName("inputNome")
        self.gridLayout_2.addWidget(self.inputNome, 2, 3, 1, 1)
        self.textoNome_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_2.setFont(font)
        self.textoNome_2.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_2.setObjectName("textoNome_2")
        self.gridLayout_2.addWidget(self.textoNome_2, 3, 2, 1, 1)
        self.inputEmpresa = QtWidgets.QLineEdit(self.tab)
        self.inputEmpresa.setObjectName("inputEmpresa")
        self.gridLayout_2.addWidget(self.inputEmpresa, 3, 3, 1, 1)
        self.inputData = QtWidgets.QDateEdit(self.tab)
        self.inputData.setObjectName("inputData")
        self.gridLayout_2.addWidget(self.inputData, 6, 3, 1, 1)
        self.textoNome_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_10.setFont(font)
        self.textoNome_10.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_10.setObjectName("textoNome_10")
        self.gridLayout_2.addWidget(self.textoNome_10, 7, 2, 1, 1)
        self.textoNome_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_4.setFont(font)
        self.textoNome_4.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_4.setObjectName("textoNome_4")
        self.gridLayout_2.addWidget(self.textoNome_4, 5, 2, 1, 1)
        self.textoNome_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_5.setFont(font)
        self.textoNome_5.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_5.setObjectName("textoNome_5")
        self.gridLayout_2.addWidget(self.textoNome_5, 6, 2, 1, 1)
        self.inputVara = QtWidgets.QLineEdit(self.tab)
        self.inputVara.setObjectName("inputVara")
        self.gridLayout_2.addWidget(self.inputVara, 8, 3, 1, 1)
        self.inputAudiencia = QtWidgets.QLineEdit(self.tab)
        self.inputAudiencia.setObjectName("inputAudiencia")
        self.gridLayout_2.addWidget(self.inputAudiencia, 5, 3, 1, 1)
        self.textoNome_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_7.setFont(font)
        self.textoNome_7.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_7.setObjectName("textoNome_7")
        self.gridLayout_2.addWidget(self.textoNome_7, 9, 2, 1, 1)
        self.inputEndereco = QtWidgets.QLineEdit(self.tab)
        self.inputEndereco.setObjectName("inputEndereco")
        self.gridLayout_2.addWidget(self.inputEndereco, 9, 3, 1, 1)
        self.inputHora = QtWidgets.QTimeEdit(self.tab)
        self.inputHora.setObjectName("inputHora")
        self.gridLayout_2.addWidget(self.inputHora, 7, 3, 1, 1)
        self.textoNome_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_6.setFont(font)
        self.textoNome_6.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_6.setObjectName("textoNome_6")
        self.gridLayout_2.addWidget(self.textoNome_6, 8, 2, 1, 1)
        self.textoNome_8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_8.setFont(font)
        self.textoNome_8.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_8.setObjectName("textoNome_8")
        self.gridLayout_2.addWidget(self.textoNome_8, 10, 2, 1, 1)
        self.inputConteudo = QtWidgets.QLineEdit(self.tab)
        self.inputConteudo.setObjectName("inputConteudo")
        self.gridLayout_2.addWidget(self.inputConteudo, 10, 3, 1, 1)
        self.botaoGerar = QtWidgets.QPushButton(self.tab)
        self.botaoGerar.setMinimumSize(QtCore.QSize(0, 40))
        self.botaoGerar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoGerar.setObjectName("botaoGerar")
        self.gridLayout_2.addWidget(self.botaoGerar, 12, 3, 1, 1)
        self.Titulo = QtWidgets.QLabel(self.tab)
        self.Titulo.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Titulo.setFont(font)
        self.Titulo.setTextFormat(QtCore.Qt.RichText)
        self.Titulo.setObjectName("Titulo")
        self.gridLayout_2.addWidget(self.Titulo, 0, 0, 1, 4)
        self.textoFinal = QtWidgets.QTextEdit(self.tab)
        self.textoFinal.setObjectName("textoFinal")
        self.gridLayout_2.addWidget(self.textoFinal, 13, 0, 1, 5)
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Titulo_2 = QtWidgets.QLabel(self.tab_2)
        self.Titulo_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Titulo_2.setFont(font)
        self.Titulo_2.setTextFormat(QtCore.Qt.RichText)
        self.Titulo_2.setObjectName("Titulo_2")
        self.gridLayout_3.addWidget(self.Titulo_2, 0, 0, 1, 3)
        self.textoNome_13 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_13.setFont(font)
        self.textoNome_13.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_13.setObjectName("textoNome_13")
        self.gridLayout_3.addWidget(self.textoNome_13, 1, 0, 1, 1)
        self.inputNome_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputNome_2.setObjectName("inputNome_2")
        self.gridLayout_3.addWidget(self.inputNome_2, 1, 1, 1, 2)
        self.textoNome_17 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_17.setFont(font)
        self.textoNome_17.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_17.setObjectName("textoNome_17")
        self.gridLayout_3.addWidget(self.textoNome_17, 2, 0, 1, 1)
        self.inputReclamante = QtWidgets.QLineEdit(self.tab_2)
        self.inputReclamante.setObjectName("inputReclamante")
        self.gridLayout_3.addWidget(self.inputReclamante, 2, 1, 1, 2)
        self.textoNome_19 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_19.setFont(font)
        self.textoNome_19.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_19.setObjectName("textoNome_19")
        self.gridLayout_3.addWidget(self.textoNome_19, 3, 0, 1, 1)
        self.inputEmpresa_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputEmpresa_2.setObjectName("inputEmpresa_2")
        self.gridLayout_3.addWidget(self.inputEmpresa_2, 3, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 3, 2, 1, 1)
        self.textoNome_16 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_16.setFont(font)
        self.textoNome_16.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_16.setObjectName("textoNome_16")
        self.gridLayout_3.addWidget(self.textoNome_16, 4, 0, 1, 1)
        self.inputAudiencia_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputAudiencia_2.setObjectName("inputAudiencia_2")
        self.gridLayout_3.addWidget(self.inputAudiencia_2, 4, 1, 1, 2)
        self.textoNome_20 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_20.setFont(font)
        self.textoNome_20.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_20.setObjectName("textoNome_20")
        self.gridLayout_3.addWidget(self.textoNome_20, 5, 0, 1, 1)
        self.inputData_2 = QtWidgets.QDateEdit(self.tab_2)
        self.inputData_2.setObjectName("inputData_2")
        self.gridLayout_3.addWidget(self.inputData_2, 5, 1, 1, 2)
        self.textoNome_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_11.setFont(font)
        self.textoNome_11.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_11.setObjectName("textoNome_11")
        self.gridLayout_3.addWidget(self.textoNome_11, 6, 0, 1, 1)
        self.inputHora_2 = QtWidgets.QTimeEdit(self.tab_2)
        self.inputHora_2.setObjectName("inputHora_2")
        self.gridLayout_3.addWidget(self.inputHora_2, 6, 1, 1, 2)
        self.textoNome_15 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_15.setFont(font)
        self.textoNome_15.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_15.setObjectName("textoNome_15")
        self.gridLayout_3.addWidget(self.textoNome_15, 7, 0, 1, 1)
        self.inputVara_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputVara_2.setObjectName("inputVara_2")
        self.gridLayout_3.addWidget(self.inputVara_2, 7, 1, 1, 2)
        self.textoNome_12 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_12.setFont(font)
        self.textoNome_12.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_12.setObjectName("textoNome_12")
        self.gridLayout_3.addWidget(self.textoNome_12, 8, 0, 1, 1)
        self.inputEndereco_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputEndereco_2.setObjectName("inputEndereco_2")
        self.gridLayout_3.addWidget(self.inputEndereco_2, 8, 1, 1, 2)
        self.textoNome_14 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_14.setFont(font)
        self.textoNome_14.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_14.setObjectName("textoNome_14")
        self.gridLayout_3.addWidget(self.textoNome_14, 9, 0, 1, 1)
        self.inputConteudo_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputConteudo_2.setObjectName("inputConteudo_2")
        self.gridLayout_3.addWidget(self.inputConteudo_2, 9, 1, 1, 2)
        self.textoNome_18 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_18.setFont(font)
        self.textoNome_18.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_18.setObjectName("textoNome_18")
        self.gridLayout_3.addWidget(self.textoNome_18, 10, 0, 1, 1)
        self.inputAdvogado_2 = QtWidgets.QLineEdit(self.tab_2)
        self.inputAdvogado_2.setObjectName("inputAdvogado_2")
        self.gridLayout_3.addWidget(self.inputAdvogado_2, 10, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 11, 0, 1, 1)
        self.botaoGerar_2 = QtWidgets.QPushButton(self.tab_2)
        self.botaoGerar_2.setMinimumSize(QtCore.QSize(0, 40))
        self.botaoGerar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoGerar_2.setObjectName("botaoGerar_2")
        self.gridLayout_3.addWidget(self.botaoGerar_2, 11, 1, 1, 2)
        self.textoFinal_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textoFinal_2.setObjectName("textoFinal_2")
        self.gridLayout_3.addWidget(self.textoFinal_2, 12, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.inputEmpresa_4 = QtWidgets.QLineEdit(self.tab_3)
        self.inputEmpresa_4.setObjectName("inputEmpresa_4")
        self.gridLayout_4.addWidget(self.inputEmpresa_4, 3, 1, 1, 1)
        self.textoNome_36 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_36.setFont(font)
        self.textoNome_36.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_36.setObjectName("textoNome_36")
        self.gridLayout_4.addWidget(self.textoNome_36, 5, 0, 1, 1)
        self.textoNome_33 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_33.setFont(font)
        self.textoNome_33.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_33.setObjectName("textoNome_33")
        self.gridLayout_4.addWidget(self.textoNome_33, 6, 0, 1, 1)
        self.inputReclamante_3 = QtWidgets.QLineEdit(self.tab_3)
        self.inputReclamante_3.setObjectName("inputReclamante_3")
        self.gridLayout_4.addWidget(self.inputReclamante_3, 2, 1, 1, 2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_4.addWidget(self.checkBox_4, 3, 2, 1, 1)
        self.textoNome_37 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_37.setFont(font)
        self.textoNome_37.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_37.setObjectName("textoNome_37")
        self.gridLayout_4.addWidget(self.textoNome_37, 4, 0, 1, 1)
        self.textoNome_39 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_39.setFont(font)
        self.textoNome_39.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_39.setObjectName("textoNome_39")
        self.gridLayout_4.addWidget(self.textoNome_39, 7, 0, 1, 1)
        self.inputData_4 = QtWidgets.QDateEdit(self.tab_3)
        self.inputData_4.setObjectName("inputData_4")
        self.gridLayout_4.addWidget(self.inputData_4, 5, 1, 1, 2)
        self.inputAudiencia_4 = QtWidgets.QLineEdit(self.tab_3)
        self.inputAudiencia_4.setObjectName("inputAudiencia_4")
        self.gridLayout_4.addWidget(self.inputAudiencia_4, 4, 1, 1, 2)
        self.textoNome_31 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_31.setFont(font)
        self.textoNome_31.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_31.setObjectName("textoNome_31")
        self.gridLayout_4.addWidget(self.textoNome_31, 2, 0, 1, 1)
        self.inputHora_4 = QtWidgets.QTimeEdit(self.tab_3)
        self.inputHora_4.setObjectName("inputHora_4")
        self.gridLayout_4.addWidget(self.inputHora_4, 6, 1, 1, 2)
        self.Titulo_4 = QtWidgets.QLabel(self.tab_3)
        self.Titulo_4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Titulo_4.setFont(font)
        self.Titulo_4.setTextFormat(QtCore.Qt.RichText)
        self.Titulo_4.setObjectName("Titulo_4")
        self.gridLayout_4.addWidget(self.Titulo_4, 0, 0, 1, 3)
        self.inputNome_4 = QtWidgets.QLineEdit(self.tab_3)
        self.inputNome_4.setObjectName("inputNome_4")
        self.gridLayout_4.addWidget(self.inputNome_4, 1, 1, 1, 2)
        self.textoNome_38 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_38.setFont(font)
        self.textoNome_38.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_38.setObjectName("textoNome_38")
        self.gridLayout_4.addWidget(self.textoNome_38, 1, 0, 1, 1)
        self.inputVara_4 = QtWidgets.QLineEdit(self.tab_3)
        self.inputVara_4.setObjectName("inputVara_4")
        self.gridLayout_4.addWidget(self.inputVara_4, 7, 1, 1, 2)
        self.textoNome_35 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_35.setFont(font)
        self.textoNome_35.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_35.setObjectName("textoNome_35")
        self.gridLayout_4.addWidget(self.textoNome_35, 8, 0, 1, 1)
        self.textoNome_32 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_32.setFont(font)
        self.textoNome_32.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_32.setObjectName("textoNome_32")
        self.gridLayout_4.addWidget(self.textoNome_32, 3, 0, 1, 1)
        self.meet = QtWidgets.QCheckBox(self.tab_3)
        self.meet.setObjectName("meet")
        self.gridLayout_4.addWidget(self.meet, 8, 2, 1, 1)
        self.inputAdvogado_4 = QtWidgets.QLineEdit(self.tab_3)
        self.inputAdvogado_4.setObjectName("inputAdvogado_4")
        self.gridLayout_4.addWidget(self.inputAdvogado_4, 11, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 12, 0, 1, 1)
        self.textoNome_40 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_40.setFont(font)
        self.textoNome_40.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_40.setObjectName("textoNome_40")
        self.gridLayout_4.addWidget(self.textoNome_40, 10, 0, 1, 1)
        self.textoNome_34 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_34.setFont(font)
        self.textoNome_34.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_34.setObjectName("textoNome_34")
        self.gridLayout_4.addWidget(self.textoNome_34, 11, 0, 1, 1)
        self.textoFinal_4 = QtWidgets.QTextEdit(self.tab_3)
        self.textoFinal_4.setObjectName("textoFinal_4")
        self.gridLayout_4.addWidget(self.textoFinal_4, 13, 0, 1, 3)
        self.inputConteudo_4 = QtWidgets.QLineEdit(self.tab_3)
        self.inputConteudo_4.setObjectName("inputConteudo_4")
        self.gridLayout_4.addWidget(self.inputConteudo_4, 10, 1, 1, 2)
        self.botaoGerar_4 = QtWidgets.QPushButton(self.tab_3)
        self.botaoGerar_4.setMinimumSize(QtCore.QSize(0, 40))
        self.botaoGerar_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoGerar_4.setObjectName("botaoGerar_4")
        self.gridLayout_4.addWidget(self.botaoGerar_4, 12, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 9, 0, 1, 1)
        self.inputLink = QtWidgets.QLineEdit(self.tab_3)
        self.inputLink.setObjectName("inputLink")
        self.gridLayout_4.addWidget(self.inputLink, 8, 1, 1, 1)
        self.inputCodigo = QtWidgets.QLineEdit(self.tab_3)
        self.inputCodigo.setObjectName("inputCodigo")
        self.gridLayout_4.addWidget(self.inputCodigo, 9, 1, 1, 1)
        self.inputSenha = QtWidgets.QLineEdit(self.tab_3)
        self.inputSenha.setObjectName("inputSenha")
        self.gridLayout_4.addWidget(self.inputSenha, 9, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Titulo_5 = QtWidgets.QLabel(self.tab_4)
        self.Titulo_5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Titulo_5.setFont(font)
        self.Titulo_5.setTextFormat(QtCore.Qt.RichText)
        self.Titulo_5.setObjectName("Titulo_5")
        self.gridLayout_5.addWidget(self.Titulo_5, 0, 0, 1, 3)
        self.textoNome_43 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_43.setFont(font)
        self.textoNome_43.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_43.setObjectName("textoNome_43")
        self.gridLayout_5.addWidget(self.textoNome_43, 1, 0, 1, 1)
        self.inputNome_5 = QtWidgets.QLineEdit(self.tab_4)
        self.inputNome_5.setObjectName("inputNome_5")
        self.gridLayout_5.addWidget(self.inputNome_5, 1, 1, 1, 2)
        self.textoNome_48 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_48.setFont(font)
        self.textoNome_48.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_48.setObjectName("textoNome_48")
        self.gridLayout_5.addWidget(self.textoNome_48, 2, 0, 1, 1)
        self.inputReclamante_4 = QtWidgets.QLineEdit(self.tab_4)
        self.inputReclamante_4.setObjectName("inputReclamante_4")
        self.gridLayout_5.addWidget(self.inputReclamante_4, 2, 1, 1, 2)
        self.textoNome_46 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_46.setFont(font)
        self.textoNome_46.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_46.setObjectName("textoNome_46")
        self.gridLayout_5.addWidget(self.textoNome_46, 3, 0, 1, 1)
        self.inputEmpresa_5 = QtWidgets.QLineEdit(self.tab_4)
        self.inputEmpresa_5.setObjectName("inputEmpresa_5")
        self.gridLayout_5.addWidget(self.inputEmpresa_5, 3, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_5.addWidget(self.checkBox_5, 3, 2, 1, 1)
        self.textoNome_49 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_49.setFont(font)
        self.textoNome_49.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_49.setObjectName("textoNome_49")
        self.gridLayout_5.addWidget(self.textoNome_49, 4, 0, 1, 1)
        self.inputAudiencia_5 = QtWidgets.QLineEdit(self.tab_4)
        self.inputAudiencia_5.setObjectName("inputAudiencia_5")
        self.gridLayout_5.addWidget(self.inputAudiencia_5, 4, 1, 1, 2)
        self.textoNome_41 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_41.setFont(font)
        self.textoNome_41.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_41.setObjectName("textoNome_41")
        self.gridLayout_5.addWidget(self.textoNome_41, 5, 0, 1, 1)
        self.inputData_5 = QtWidgets.QDateEdit(self.tab_4)
        self.inputData_5.setObjectName("inputData_5")
        self.gridLayout_5.addWidget(self.inputData_5, 5, 1, 1, 2)
        self.textoNome_47 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_47.setFont(font)
        self.textoNome_47.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_47.setObjectName("textoNome_47")
        self.gridLayout_5.addWidget(self.textoNome_47, 6, 0, 1, 1)
        self.inputHora_5 = QtWidgets.QTimeEdit(self.tab_4)
        self.inputHora_5.setObjectName("inputHora_5")
        self.gridLayout_5.addWidget(self.inputHora_5, 6, 1, 1, 2)
        self.textoNome_50 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_50.setFont(font)
        self.textoNome_50.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_50.setObjectName("textoNome_50")
        self.gridLayout_5.addWidget(self.textoNome_50, 7, 0, 1, 1)
        self.inputVara_5 = QtWidgets.QLineEdit(self.tab_4)
        self.inputVara_5.setObjectName("inputVara_5")
        self.gridLayout_5.addWidget(self.inputVara_5, 7, 1, 1, 2)
        self.textoNome_42 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_42.setFont(font)
        self.textoNome_42.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_42.setObjectName("textoNome_42")
        self.gridLayout_5.addWidget(self.textoNome_42, 8, 0, 1, 1)
        self.inputLink_2 = QtWidgets.QLineEdit(self.tab_4)
        self.inputLink_2.setObjectName("inputLink_2")
        self.gridLayout_5.addWidget(self.inputLink_2, 8, 1, 1, 1)
        self.meet_2 = QtWidgets.QCheckBox(self.tab_4)
        self.meet_2.setObjectName("meet_2")
        self.gridLayout_5.addWidget(self.meet_2, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 9, 0, 1, 1)
        self.inputCodigo_2 = QtWidgets.QLineEdit(self.tab_4)
        self.inputCodigo_2.setObjectName("inputCodigo_2")
        self.gridLayout_5.addWidget(self.inputCodigo_2, 9, 1, 1, 1)
        self.inputSenha_2 = QtWidgets.QLineEdit(self.tab_4)
        self.inputSenha_2.setObjectName("inputSenha_2")
        self.gridLayout_5.addWidget(self.inputSenha_2, 9, 2, 1, 1)
        self.textoNome_44 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_44.setFont(font)
        self.textoNome_44.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_44.setObjectName("textoNome_44")
        self.gridLayout_5.addWidget(self.textoNome_44, 10, 0, 1, 1)
        self.inputConteudo_5 = QtWidgets.QLineEdit(self.tab_4)
        self.inputConteudo_5.setObjectName("inputConteudo_5")
        self.gridLayout_5.addWidget(self.inputConteudo_5, 10, 1, 1, 2)
        self.textoNome_45 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textoNome_45.setFont(font)
        self.textoNome_45.setTextFormat(QtCore.Qt.RichText)
        self.textoNome_45.setObjectName("textoNome_45")
        self.gridLayout_5.addWidget(self.textoNome_45, 11, 0, 1, 1)
        self.inputAdvogado_5 = QtWidgets.QLineEdit(self.tab_4)
        self.inputAdvogado_5.setObjectName("inputAdvogado_5")
        self.gridLayout_5.addWidget(self.inputAdvogado_5, 11, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 12, 0, 1, 1)
        self.botaoGerar_5 = QtWidgets.QPushButton(self.tab_4)
        self.botaoGerar_5.setMinimumSize(QtCore.QSize(0, 40))
        self.botaoGerar_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoGerar_5.setObjectName("botaoGerar_5")
        self.gridLayout_5.addWidget(self.botaoGerar_5, 12, 1, 1, 2)
        self.textoFinal_5 = QtWidgets.QTextEdit(self.tab_4)
        self.textoFinal_5.setObjectName("textoFinal_5")
        self.gridLayout_5.addWidget(self.textoFinal_5, 13, 0, 1, 3)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        WindowComumReclamante.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowComumReclamante)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(WindowComumReclamante)

    def retranslateUi(self, WindowComumReclamante):
        _translate = QtCore.QCoreApplication.translate
        WindowComumReclamante.setWindowTitle(_translate("WindowComumReclamante", "Intimações"))
        self.textoNome_9.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Advogado:</span></p></body></html>"))
        self.textoNome.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Nome:</span></p></body></html>"))
        self.textoNome_3.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Primeira designação:</span></p></body></html>"))
        self.textoNome_2.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Empresa:</span></p></body></html>"))
        self.textoNome_10.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hora:</span></p></body></html>"))
        self.textoNome_4.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Tipo de Audiência:</span></p></body></html>"))
        self.textoNome_5.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Data:</span></p></body></html>"))
        self.textoNome_7.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Endereço:</span></p></body></html>"))
        self.textoNome_6.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Vara:</span></p></body></html>"))
        self.textoNome_8.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Mensagem:</span></p></body></html>"))
        self.botaoGerar.setText(_translate("WindowComumReclamante", "Gerar Intimação"))
        self.Titulo.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:xx-large; font-weight:600;\">Intimação Comum Reclamante</span></p></body></html>"))
        self.checkBox.setText(_translate("WindowComumReclamante", "(Caso for redesignação, deixar marcado)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WindowComumReclamante", "Comum (Reclamante)"))
        self.Titulo_2.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:xx-large; font-weight:600;\">Intimação Comum Testemunha</span></p></body></html>"))
        self.textoNome_13.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Nome:</span></p></body></html>"))
        self.textoNome_17.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Reclamante:</span></p></body></html>"))
        self.textoNome_19.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Empresa:</span></p></body></html>"))
        self.checkBox_2.setText(_translate("WindowComumReclamante", "(Caso for redesignação, deixar marcado)"))
        self.textoNome_16.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Tipo de Audiência:</span></p></body></html>"))
        self.textoNome_20.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Data:</span></p></body></html>"))
        self.textoNome_11.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hora:</span></p></body></html>"))
        self.textoNome_15.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Vara:</span></p></body></html>"))
        self.textoNome_12.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Endereço:</span></p></body></html>"))
        self.textoNome_14.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Mensagem:</span></p></body></html>"))
        self.textoNome_18.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Advogado:</span></p></body></html>"))
        self.botaoGerar_2.setText(_translate("WindowComumReclamante", "Gerar Intimação"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WindowComumReclamante", "Comum (Testemunha)"))
        self.textoNome_36.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Data:</span></p></body></html>"))
        self.textoNome_33.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hora:</span></p></body></html>"))
        self.checkBox_4.setText(_translate("WindowComumReclamante", "(Caso for redesignação, deixar marcado)"))
        self.textoNome_37.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Tipo de Audiência:</span></p></body></html>"))
        self.textoNome_39.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Vara:</span></p></body></html>"))
        self.textoNome_31.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Reclamante:</span></p></body></html>"))
        self.Titulo_4.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:xx-large; font-weight:600;\">Intimação Vídeo Reclamante</span></p></body></html>"))
        self.textoNome_38.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Nome:</span></p></body></html>"))
        self.textoNome_35.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Link:</span></p></body></html>"))
        self.textoNome_32.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Empresa:</span></p></body></html>"))
        self.meet.setText(_translate("WindowComumReclamante", "(Caso for no Meet, deixar marcado)"))
        self.textoNome_40.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Mensagem:</span></p></body></html>"))
        self.textoNome_34.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Advogado:</span></p></body></html>"))
        self.botaoGerar_4.setText(_translate("WindowComumReclamante", "Gerar Intimação"))
        self.label_2.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Código e Senha:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WindowComumReclamante", "Video (Reclamante)"))
        self.Titulo_5.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:xx-large; font-weight:600;\">Intimação Vídeo Testemunha</span></p></body></html>"))
        self.textoNome_43.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Nome:</span></p></body></html>"))
        self.textoNome_48.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Reclamante:</span></p></body></html>"))
        self.textoNome_46.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Empresa:</span></p></body></html>"))
        self.checkBox_5.setText(_translate("WindowComumReclamante", "(Caso for redesignação, deixar marcado)"))
        self.textoNome_49.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Tipo de Audiência:</span></p></body></html>"))
        self.textoNome_41.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Data:</span></p></body></html>"))
        self.textoNome_47.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hora:</span></p></body></html>"))
        self.textoNome_50.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Vara:</span></p></body></html>"))
        self.textoNome_42.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Link:</span></p></body></html>"))
        self.meet_2.setText(_translate("WindowComumReclamante", "(Caso for no Meet, deixar marcado)"))
        self.label_3.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Código e Senha:</span></p></body></html>"))
        self.textoNome_44.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Mensagem:</span></p></body></html>"))
        self.textoNome_45.setText(_translate("WindowComumReclamante", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Advogado:</span></p></body></html>"))
        self.botaoGerar_5.setText(_translate("WindowComumReclamante", "Gerar Intimação"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("WindowComumReclamante", "Video (Testemunha)"))
